#!/bin/bash
# --hookpoints layers.10.mlp layers.15.mlp layers.20.mlp \
uv run python -m sparsify \
"HuggingFaceTB/SmolLM2-135M" --transcode=True --skip_connection=True \
--loss_fn=ce \
--wandb_project=optimized-encoder \
--run_name sae-pkm/$1 ${@:2}
