#!/bin/bash
K=$1
EF=$2
WANDB_ENTITY=eleutherai uv run python -m sparsify \
nev/GELU_4L512W_C4_Code \
--ctx_len 1024 \
--transcode=True \
--batch_size=16 --expansion_factor=$EF \
--optimizer=muon --lr=5e-4 \
--k=$K \
--hookpoints h.0.mlp h.1.mlp h.2.mlp h.3.mlp \
--run_name gelu-4l-clt-sweep/k$K-x$EF$3 \
--skip_connection=True \
${@:4} \
--cross_layer 4
