#!/bin/bash
# export LD_LIBRARY_PATH=/usr/local/cuda-12.8/lib64:$LD_LIBRARY_PATH
# export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
# export PATH=/usr/local/cuda-12.8/bin:$PATH

# WANDB_ENTITY=eleutherai  \
SPARSIFY_DISTRIBUTE_MODEL=0 uv run torchrun --nproc_per_node=gpu -m sparsify \
google/gemma-2-2b EleutherAI/fineweb-edu-dedup-10b \
--ctx_len 128 \
--transcode=True \
--batch_size=2 --expansion_factor=8 \
--k=32 \
--run_name gemma-2-2b/$1 ${@:2} \
--skip_connection=True \
--tp=2 \
--layers 3 \
--activation groupmax
