#!/bin/bash
WANDB_ENTITY=eleutherai uv run torchrun --master_port 8954 --nproc_per_node gpu -m sparsify \
roneneldan/TinyStories-33M roneneldan/TinyStories \
--transcode=True --skip_connection=True \
--batch_size=8 --expansion_factor=32 --tp=4 \
--hookpoints h.0.mlp h.1.mlp h.2.mlp h.3.mlp \
--run_name non-clt-ts/$1 ${@:2}
